version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cicd/test
    overwrite: yes
permisstions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: /home/ubuntu/cicd/test/deploy.sh
      timeout: 60
      runas: ubuntu